services:
    sip2mqtt:
        image: 'sip2mqtt:latest'
        build:
            dockerfile: 'Containerfile'
            context: '../'
        ports:
            - '55060:55060/udp'
        env_file: config.env
        restart: always
